### ISSUE TITLE
 ISP-6CE554 (E554) autodetected but timed out

### ISSUE THREAD

**Issue by eherranzr** [8none1/idealLED#15]
I installed the Custom Components and auto detected my device  ISP-6CE554 (E554) 

Nonetheless, when trying to connect, log shows the following:
`2024-12-27 14:31:05.388 ERROR (Dummy-1) [custom_components.ideal_led.idealled] Error getting status: ISP-6CE554 - C5:B6:4F:6C:E5:54: Failed to connect after 4 attempt(s): TimeoutError`

If useful, I was able to use them by using ESPHome using the following code, but I would prefer to use the custom component and free an ESP32:
````
ble_client:
  - mac_address: ####REDACTED
    auto_connect: true
    id: luces_navidad
    on_connect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Connected to BLE device");
    on_disconnect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Disconnected from BLE device");

switch:
  - platform: ble_client
    ble_client_id: luces_navidad 
    name: "Conexión Luces Navidad"
  - platform: template
    name: "Apagar Luces Navidad"
    turn_on_action:
      - ble_client.ble_write:
          id: luces_navidad
          service_uuid: 0000fff0-0000-1000-8000-00805f9b34fb
          characteristic_uuid: d44bc439-abfd-45a2-b575-925416129600
          # List of bytes to write.
          #value: [0x01, 0xab, 0xff] Example
          value: [0x79, 0xd1, 0xdb, 0xa4, 0x9, 0x19, 0xc2, 0x46, 0xa8, 0x58, 0x0a, 0xe7, 0xd1, 0x1b, 0x78, 0x84]
  - platform: template
    name: "Encender Luces Navidad"
    turn_on_action:
      - ble_client.ble_write:
          id: luces_navidad
          service_uuid: 0000fff0-0000-1000-8000-00805f9b34fb
          characteristic_uuid: d44bc439-abfd-45a2-b575-925416129600
          # List of bytes to write.
          #value: [0x01, 0xab, 0xff] Example
          value: [0x84, 0xdd, 0x50, 0x42, 0x37, 0x41, 0x50, 0x89, 0x7a, 0xc8, 0x2f, 0x39, 0x11, 0x9, 0x68, 0xa8]
````

Any idea what the issue may be?

**Comment by 8none1** [comment]
This error:
`ISP-6CE554 - C5:B6:4F:6C:E5:54: Failed to connect after 4 attempt(s): TimeoutError`

points to the Home Assistant installation not being able to communicate with the iDeal device.  Most likely because it is out of range.

The simplest way to troubleshoot this will be to move the LED devices closer to your Home Assistant installation and try again.  
Another option would be to set up an ESP32 as a [Bluetooth proxy using ESPHome](https://esphome.io/components/bluetooth_proxy.html).


If the bytes from the integration code control the lights correctly via ESPhome directly, that suggests that the integration will work once Home Assistant can "see" the device.

**Comment by eherranzr** [comment]
That's weird because

1. The device is detected by Home Assistant and request me to configure
2. I have several Bluetooth proxy devices around my house that are used in Home Assistant to, amongst other things, get temperature and humidity values from Xiaomi thermometers that are just beside the LED device.

I'll try to bring closer the LED device to the Home Assistant instalation anyway and report back

**Comment by 8none1** [comment]
It's also possible that the LED device is in use by something else, for example the app or another HA instance.

**Comment by 8none1** [comment]
There is a new version,  please upgrade from HACS or pull the main branch.

**Comment by eherranzr** [comment]
I upgraded via HACS but still getting the same error.

Tested the integration:
1. Using several ESPHome Bluetooth Proxy around the house that are confirmed to be working as they are getting data from other devices
2. With the LED device close to HA installation device
3. Without any device connected to the LED device (can confirm that the app phone sees the LEDs but is not connected nor any other device does)

Are there any debug logs that I may be able to provide. It seems very strange for the integration not being able to connect with ESPHome does.

**Comment by 8none1** [comment]
Please can you:
 - remove the devices from HA
 - Enable debug logging for the integration
 - re-add the device
 - (see what happens)
 - turn off debug logging and attach the file to this issue

![image](https://github.com/user-attachments/assets/28caf7f7-6509-434f-beac-e169ffb1d77b)

**Comment by eherranzr** [comment]
Is there any workaround (something that I can input in yaml as [this](https://community.home-assistant.io/t/enable-debug-logging-for-integrations-am-i-missing-something/500256/6)?)
Unfortunately, as I'm unable to add the device to HA, I do not have the integration available in my UI and thus, cannot enable debug logging

**Comment by 8none1** [comment]
Add something like this to your `configuration.yaml`:

```yaml
logger:
  default: info
  logs:
    homeassistant.components.cloud: debug
    custom_components: debug
```
