### ISSUE TITLE
does not add a device

### ISSUE THREAD

**Issue by ops244** [8none1/idealLED#17]
there's nowhere to delete it, he didn't even add it.

**Comment by 8none1** [comment]
Best guess is that your device uses a new protocol which is not supported or is not responding to the request to report it's firmware version.  However, I can't be sure because the debug level logging is not in the log file attached.

How are you enabling the debug logging?

**Comment by ops244** [comment]
this is not a debugging log, this is a regular home assistant core log.

I can't turn on the debugging log, because the integration isn't being installed, and it's not being installed because it doesn't add a device, which is a dead end...

**Comment by ops244** [comment]
By the way, the garland turns on at the same time.

**Comment by 8none1** [comment]
Add something like this to your `configuration.yaml`:

```yaml
logger:
  default: info
  logs:
    homeassistant.components.cloud: debug
    custom_components: debug
```
